### ISSUE TITLE
Google tag manager 

### ISSUE THREAD

**Issue by ghost** [esl/virtual-elixirconf-eu-jekyll#7]
Needs to be updated/made correct for virtual.elixirconf.eu 

The tag manager stuff is still as it was when I imported it 2 months ago https://github.com/esl/virtual-elixirconf-eu-jekyll/blame/master/_layouts/default.html#L8

Hmm - and it’s also in the head import (also as I imported 2 months ago)  https://github.com/esl/virtual-elixirconf-eu-jekyll/blame/master/_includes/imports/head.html#L17

So in the <html><head><script.. we load the script and initialise it, then on the default layout (the index page) we also bring in google tag manager via an iframe.. Seems a bit confused

**Comment by michael-j1210** [comment]
Im working to resolve
